apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: main-container
      image: my-image
      command: ["sh", "-c", "echo Hello from the main container!"]
  initContainers:
    - name: init-container
      image: busybox
      command: ["sh", "-c", "echo Hello from the init container!"]